[2023-02-15T12:21:55.168+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: sample.task3 manual__2023-02-15T12:21:29.167554+00:00 [queued]>
[2023-02-15T12:21:55.187+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: sample.task3 manual__2023-02-15T12:21:29.167554+00:00 [queued]>
[2023-02-15T12:21:55.188+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-15T12:21:55.188+0000] {taskinstance.py:1280} INFO - Starting attempt 5 of 6
[2023-02-15T12:21:55.188+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-15T12:21:55.221+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): task3> on 2023-02-15 12:21:29.167554+00:00
[2023-02-15T12:21:55.228+0000] {standard_task_runner.py:55} INFO - Started process 4514 to run task
[2023-02-15T12:21:55.234+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sample', 'task3', 'manual__2023-02-15T12:21:29.167554+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/sample.py', '--cfg-path', '/tmp/tmpvg1i6dz9']
[2023-02-15T12:21:55.235+0000] {standard_task_runner.py:83} INFO - Job 69: Subtask task3
[2023-02-15T12:21:55.352+0000] {task_command.py:388} INFO - Running <TaskInstance: sample.task3 manual__2023-02-15T12:21:29.167554+00:00 [running]> on host 6ef058fcda8d
[2023-02-15T12:21:55.477+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sample
AIRFLOW_CTX_TASK_ID=task3
AIRFLOW_CTX_EXECUTION_DATE=2023-02-15T12:21:29.167554+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-15T12:21:29.167554+00:00
[2023-02-15T12:21:55.478+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-15T12:21:55.480+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 125']
[2023-02-15T12:21:55.503+0000] {subprocess.py:86} INFO - Output:
[2023-02-15T12:21:55.507+0000] {subprocess.py:97} INFO - Command exited with return code 125
[2023-02-15T12:21:55.527+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2023-02-15T12:21:55.534+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=sample, task_id=task3, execution_date=20230215T122129, start_date=20230215T122155, end_date=20230215T122155
[2023-02-15T12:21:55.555+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 69 for task task3 (Bash command failed. The command returned a non-zero exit code 125.; 4514)
[2023-02-15T12:21:55.605+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-15T12:21:55.657+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
