[2023-02-16T04:36:05.726+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: example_dag.task3 manual__2023-02-16T04:35:34.409814+00:00 [queued]>
[2023-02-16T04:36:05.747+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: example_dag.task3 manual__2023-02-16T04:35:34.409814+00:00 [queued]>
[2023-02-16T04:36:05.748+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-16T04:36:05.748+0000] {taskinstance.py:1280} INFO - Starting attempt 6 of 6
[2023-02-16T04:36:05.748+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-16T04:36:05.787+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): task3> on 2023-02-16 04:35:34.409814+00:00
[2023-02-16T04:36:05.795+0000] {standard_task_runner.py:55} INFO - Started process 1103 to run task
[2023-02-16T04:36:05.802+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'example_dag', 'task3', 'manual__2023-02-16T04:35:34.409814+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/sample.py', '--cfg-path', '/tmp/tmpnugjm7z4']
[2023-02-16T04:36:05.803+0000] {standard_task_runner.py:83} INFO - Job 97: Subtask task3
[2023-02-16T04:36:05.959+0000] {task_command.py:388} INFO - Running <TaskInstance: example_dag.task3 manual__2023-02-16T04:35:34.409814+00:00 [running]> on host 6ef058fcda8d
[2023-02-16T04:36:06.200+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_dag
AIRFLOW_CTX_TASK_ID=task3
AIRFLOW_CTX_EXECUTION_DATE=2023-02-16T04:35:34.409814+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-16T04:35:34.409814+00:00
[2023-02-16T04:36:06.203+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-16T04:36:06.205+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 125']
[2023-02-16T04:36:06.228+0000] {subprocess.py:86} INFO - Output:
[2023-02-16T04:36:06.232+0000] {subprocess.py:97} INFO - Command exited with return code 125
[2023-02-16T04:36:06.255+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2023-02-16T04:36:06.263+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=example_dag, task_id=task3, execution_date=20230216T043534, start_date=20230216T043605, end_date=20230216T043606
[2023-02-16T04:36:06.298+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 97 for task task3 (Bash command failed. The command returned a non-zero exit code 125.; 1103)
[2023-02-16T04:36:06.338+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-16T04:36:06.405+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
